server:
 port: 8013


logging:
 file:
  path: log
 level:
  com:
   xiake: info
  root: error

tianx:
 APIKEY: "1534f9f2dd38af44f1e59613d4145452"

wx:
 mp:
  appId: "wx03e67a5e06ded016"
  secret: "0fd5beb1b7a490afa64e622cb97f7ea7"
  templateId: "BGBGnSBSb8movMZ7P4usaRlvrqB8YcU1B9e-Z8uTr_E"
  templateIdForNight: "81ydK9c3ISl7HbejD9haCre-X8hM2uUk6WtZvsbzbz4"
  city: "重庆"
  type: 1
  cron: "0 0 10 * * ?"
  nightCron: "0 0 0 * * ?"

info:
 list:
  - openid: "oLWdn63exrF3jHBUkKRLldUyGy-M"
    constellation: "aquarius"
  - openid: "oLWdn6w2Y1ekuTTPNCQQs3n_PB6w"
    constellation: "virgo"

url:
 msg: "https://api.tianapi.com/everyday/index"
 fortune: "https://api.tianapi.com/star/index"
 weather: "https://api.tianapi.com/tianqi/index"
 goodNight: "https://apis.tianapi.com/wanan/index"

content:
 type: "application/x-www-form-urlencoded"
spring:
 task:
  scheduling:
   pool:
    size: 2
